os:
- linux
language: ruby
install: bundle install --without development --deployment --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
rvm:
- 2.2.0
- 2.0.0
before_install:
- sudo apt-get update
- gem update --system
- gem --version
- npm install -g grunt-cli
- npm install
- npm update
before_script:
- grunt
- bundle exec rake
addons:
  code_climate:
    repo_token: 812d48041b7faafd2a04d75ecc3d59ab6e9c9586c628c9272e80cf51f56a9c62
notifications:
  slack:
    secure: c/U+pFl8S9t+IuCdNu08ldMnROlAfO3hL8cqg4e5sB82Qu9WysGrh/nxfQjd69Bk1CFmPbZVT80DD/TDMNdKPYDnJ6Brwka6O3mIBxCMTFVFjJU3BAznPGg8OvcmwCjayEDCgqZIKhATskEYgd7/K5+k1wdJOugQqUVKvbHr9Zo=
    on_success: [change] # default: change
    on_failure: [change] # default: always
deploy:
  provider: heroku
  api_key:
    secure: vQi59892dFjqpdhKrPwB6dBtCC7xtPUG5uxF842jBLH1KeZrRq2eMh/oOuQdou+kfUSj/JmhjKR5DFVAi/w+ib+VM3mQmz+bjJjQAZNexA6xglXdWBMg47QjN+sHu+baw7JY50PbD3XPuGuz0gVizNY9FHtSD6Efk1giu3gZMJQ=
  app: mvweddings
  on:
    repo: crmis/weddings
